INSERT INTO authors VALUES (1, 'Hugh Howey', current_timestamp, current_timestamp);
INSERT INTO authors VALUES (2, 'Cixin Liu', current_timestamp, current_timestamp);
INSERT INTO authors VALUES (3, 'Andy Wier', current_timestamp, current_timestamp);
INSERT INTO authors VALUES (4, 'James S.A. Corey', current_timestamp, current_timestamp);
INSERT INTO authors VALUES (5, 'Pierce Brown', current_timestamp, current_timestamp);

INSERT INTO books VALUES (1, 1, 'Wool', 2012, current_timestamp, current_timestamp);
INSERT INTO books VALUES (2, 1, 'Shift', 2013, current_timestamp, current_timestamp);
INSERT INTO books VALUES (3, 1, 'Dust', 2014, current_timestamp, current_timestamp);
INSERT INTO books VALUES (4, 4, 'Leviathan Wakes', 2011, current_timestamp, current_timestamp);
INSERT INTO books VALUES (5, 4, 'Caliban''s War', 2012, current_timestamp, current_timestamp);
INSERT INTO books VALUES (6, 4, 'Adaddon''s Gate', 2013, current_timestamp, current_timestamp);
INSERT INTO books VALUES (7, 4, 'Cibola Burn', 2014, current_timestamp, current_timestamp);
INSERT INTO books VALUES (8, 4, 'Nemesis Games', 2015, current_timestamp, current_timestamp);
INSERT INTO books VALUES (9, 4, 'Babylon''s Ashes', 2016, current_timestamp, current_timestamp);
INSERT INTO books VALUES (10, 5, 'Red Rising', 2014, current_timestamp, current_timestamp);
INSERT INTO books VALUES (11, 5, 'Golden Son', 2015, current_timestamp, current_timestamp);
INSERT INTO books VALUES (12, 5, 'Morning Star', 2016, current_timestamp, current_timestamp);
INSERT INTO books VALUES (13, 2, 'The Three-Body Problem', 2008, current_timestamp, current_timestamp);
INSERT INTO books VALUES (14, 2, 'The Dark Forest', 2008, current_timestamp, current_timestamp);
INSERT INTO books VALUES (15, 2, 'Death''s End', 2010, current_timestamp, current_timestamp);
INSERT INTO books VALUES (16, 3, 'The Martian', 2011, current_timestamp, current_timestamp);
